Settings:
  damageTitle: false
  damageHologram: false
arms:
  arm1:
    enable: true
    damage: 8
  arm2:
    enable: true
    damage: 8
  arm3:
    enable: true
    damage: 8
  arm4:
    enable: true
    damage: 8
mobs:
  mob1:
    name: '&aMOB-1'